{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.APPLE.FloatPixels
       (gl_RGB_FLOAT32_APPLE, gl_RGB_FLOAT16_APPLE, gl_RGBA_FLOAT32_APPLE,
        gl_RGBA_FLOAT16_APPLE, gl_LUMINANCE_FLOAT32_APPLE,
        gl_LUMINANCE_FLOAT16_APPLE, gl_LUMINANCE_ALPHA_FLOAT32_APPLE,
        gl_LUMINANCE_ALPHA_FLOAT16_APPLE, gl_INTENSITY_FLOAT32_APPLE,
        gl_INTENSITY_FLOAT16_APPLE, gl_HALF_APPLE, gl_COLOR_FLOAT_APPLE,
        gl_ALPHA_FLOAT32_APPLE, gl_ALPHA_FLOAT16_APPLE)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_RGB_FLOAT32_APPLE :: GLenum
gl_RGB_FLOAT32_APPLE = 34837
 
gl_RGB_FLOAT16_APPLE :: GLenum
gl_RGB_FLOAT16_APPLE = 34843
 
gl_RGBA_FLOAT32_APPLE :: GLenum
gl_RGBA_FLOAT32_APPLE = 34836
 
gl_RGBA_FLOAT16_APPLE :: GLenum
gl_RGBA_FLOAT16_APPLE = 34842
 
gl_LUMINANCE_FLOAT32_APPLE :: GLenum
gl_LUMINANCE_FLOAT32_APPLE = 34840
 
gl_LUMINANCE_FLOAT16_APPLE :: GLenum
gl_LUMINANCE_FLOAT16_APPLE = 34846
 
gl_LUMINANCE_ALPHA_FLOAT32_APPLE :: GLenum
gl_LUMINANCE_ALPHA_FLOAT32_APPLE = 34841
 
gl_LUMINANCE_ALPHA_FLOAT16_APPLE :: GLenum
gl_LUMINANCE_ALPHA_FLOAT16_APPLE = 34847
 
gl_INTENSITY_FLOAT32_APPLE :: GLenum
gl_INTENSITY_FLOAT32_APPLE = 34839
 
gl_INTENSITY_FLOAT16_APPLE :: GLenum
gl_INTENSITY_FLOAT16_APPLE = 34845
 
gl_HALF_APPLE :: GLenum
gl_HALF_APPLE = 5131
 
gl_COLOR_FLOAT_APPLE :: GLenum
gl_COLOR_FLOAT_APPLE = 35343
 
gl_ALPHA_FLOAT32_APPLE :: GLenum
gl_ALPHA_FLOAT32_APPLE = 34838
 
gl_ALPHA_FLOAT16_APPLE :: GLenum
gl_ALPHA_FLOAT16_APPLE = 34844