{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.TextureSnorm
       (gl_SIGNED_NORMALIZED, gl_RG_SNORM, gl_RGB_SNORM, gl_RGBA_SNORM,
        gl_RGBA8_SNORM, gl_RGBA16_SNORM, gl_RGB8_SNORM, gl_RGB16_SNORM,
        gl_RG8_SNORM, gl_RG16_SNORM, gl_RED_SNORM, gl_R8_SNORM,
        gl_R16_SNORM, gl_LUMINANCE_SNORM, gl_LUMINANCE_ALPHA_SNORM,
        gl_LUMINANCE8_SNORM, gl_LUMINANCE8_ALPHA8_SNORM,
        gl_LUMINANCE16_SNORM, gl_LUMINANCE16_ALPHA16_SNORM,
        gl_INTENSITY_SNORM, gl_INTENSITY8_SNORM, gl_INTENSITY16_SNORM,
        gl_ALPHA_SNORM, gl_ALPHA8_SNORM, gl_ALPHA16_SNORM)
       where
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core31
       (gl_SIGNED_NORMALIZED, gl_RG_SNORM, gl_RGB_SNORM, gl_RGBA_SNORM,
        gl_RGBA8_SNORM, gl_RGBA16_SNORM, gl_RGB8_SNORM, gl_RGB16_SNORM,
        gl_RG8_SNORM, gl_RG16_SNORM, gl_RED_SNORM, gl_R8_SNORM,
        gl_R16_SNORM)
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_LUMINANCE_SNORM :: GLenum
gl_LUMINANCE_SNORM = 36881
 
gl_LUMINANCE_ALPHA_SNORM :: GLenum
gl_LUMINANCE_ALPHA_SNORM = 36882
 
gl_LUMINANCE8_SNORM :: GLenum
gl_LUMINANCE8_SNORM = 36885
 
gl_LUMINANCE8_ALPHA8_SNORM :: GLenum
gl_LUMINANCE8_ALPHA8_SNORM = 36886
 
gl_LUMINANCE16_SNORM :: GLenum
gl_LUMINANCE16_SNORM = 36889
 
gl_LUMINANCE16_ALPHA16_SNORM :: GLenum
gl_LUMINANCE16_ALPHA16_SNORM = 36890
 
gl_INTENSITY_SNORM :: GLenum
gl_INTENSITY_SNORM = 36883
 
gl_INTENSITY8_SNORM :: GLenum
gl_INTENSITY8_SNORM = 36887
 
gl_INTENSITY16_SNORM :: GLenum
gl_INTENSITY16_SNORM = 36891
 
gl_ALPHA_SNORM :: GLenum
gl_ALPHA_SNORM = 36880
 
gl_ALPHA8_SNORM :: GLenum
gl_ALPHA8_SNORM = 36884
 
gl_ALPHA16_SNORM :: GLenum
gl_ALPHA16_SNORM = 36888