{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core15Compatibility
       (gl_WEIGHT_ARRAY_BUFFER_BINDING, gl_VERTEX_ARRAY_BUFFER_BINDING,
        gl_TEXTURE_COORD_ARRAY_BUFFER_BINDING, gl_SRC2_RGB, gl_SRC2_ALPHA,
        gl_SRC1_RGB, gl_SRC0_RGB, gl_SRC0_ALPHA,
        gl_SECONDARY_COLOR_ARRAY_BUFFER_BINDING,
        gl_NORMAL_ARRAY_BUFFER_BINDING, gl_INDEX_ARRAY_BUFFER_BINDING,
        gl_FOG_COORD_SRC, gl_FOG_COORD_ARRAY_TYPE,
        gl_FOG_COORD_ARRAY_STRIDE, gl_FOG_COORD_ARRAY_POINTER,
        gl_FOG_COORD_ARRAY_BUFFER_BINDING, gl_FOG_COORD_ARRAY,
        gl_FOG_COORDINATE_ARRAY_BUFFER_BINDING, gl_FOG_COORD,
        gl_EDGE_FLAG_ARRAY_BUFFER_BINDING, gl_CURRENT_FOG_COORD,
        gl_COLOR_ARRAY_BUFFER_BINDING)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_WEIGHT_ARRAY_BUFFER_BINDING :: GLenum
gl_WEIGHT_ARRAY_BUFFER_BINDING = 34974
 
gl_VERTEX_ARRAY_BUFFER_BINDING :: GLenum
gl_VERTEX_ARRAY_BUFFER_BINDING = 34966
 
gl_TEXTURE_COORD_ARRAY_BUFFER_BINDING :: GLenum
gl_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 34970
 
gl_SRC2_RGB :: GLenum
gl_SRC2_RGB = 34178
 
gl_SRC2_ALPHA :: GLenum
gl_SRC2_ALPHA = 34186
 
gl_SRC1_RGB :: GLenum
gl_SRC1_RGB = 34177
 
gl_SRC0_RGB :: GLenum
gl_SRC0_RGB = 34176
 
gl_SRC0_ALPHA :: GLenum
gl_SRC0_ALPHA = 34184
 
gl_SECONDARY_COLOR_ARRAY_BUFFER_BINDING :: GLenum
gl_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 34972
 
gl_NORMAL_ARRAY_BUFFER_BINDING :: GLenum
gl_NORMAL_ARRAY_BUFFER_BINDING = 34967
 
gl_INDEX_ARRAY_BUFFER_BINDING :: GLenum
gl_INDEX_ARRAY_BUFFER_BINDING = 34969
 
gl_FOG_COORD_SRC :: GLenum
gl_FOG_COORD_SRC = 33872
 
gl_FOG_COORD_ARRAY_TYPE :: GLenum
gl_FOG_COORD_ARRAY_TYPE = 33876
 
gl_FOG_COORD_ARRAY_STRIDE :: GLenum
gl_FOG_COORD_ARRAY_STRIDE = 33877
 
gl_FOG_COORD_ARRAY_POINTER :: GLenum
gl_FOG_COORD_ARRAY_POINTER = 33878
 
gl_FOG_COORD_ARRAY_BUFFER_BINDING :: GLenum
gl_FOG_COORD_ARRAY_BUFFER_BINDING = 34973
 
gl_FOG_COORD_ARRAY :: GLenum
gl_FOG_COORD_ARRAY = 33879
 
gl_FOG_COORDINATE_ARRAY_BUFFER_BINDING :: GLenum
gl_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 34973
 
gl_FOG_COORD :: GLenum
gl_FOG_COORD = 33873
 
gl_EDGE_FLAG_ARRAY_BUFFER_BINDING :: GLenum
gl_EDGE_FLAG_ARRAY_BUFFER_BINDING = 34971
 
gl_CURRENT_FOG_COORD :: GLenum
gl_CURRENT_FOG_COORD = 33875
 
gl_COLOR_ARRAY_BUFFER_BINDING :: GLenum
gl_COLOR_ARRAY_BUFFER_BINDING = 34968