module Graphics.Rendering.OpenGL.Raw.ARB.Compatibility
       (module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core30Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core21Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core20Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core15Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core14Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core13Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core12Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core11Compatibility,
        module Graphics.Rendering.OpenGL.Raw.Core.Internal.Core10Compatibility)
       where
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core10Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core11Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core12Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core13Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core14Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core15Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core20Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core21Compatibility
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core30Compatibility