{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.ARB.TextureFloat
       (gl_UNSIGNED_NORMALIZED, gl_TEXTURE_RED_TYPE,
        gl_TEXTURE_LUMINANCE_TYPE, gl_TEXTURE_INTENSITY_TYPE,
        gl_TEXTURE_GREEN_TYPE, gl_TEXTURE_DEPTH_TYPE, gl_TEXTURE_BLUE_TYPE,
        gl_TEXTURE_ALPHA_TYPE, gl_RGBA32F, gl_RGBA16F, gl_RGB32F,
        gl_RGB16F, gl_LUMINANCE_ALPHA32F, gl_LUMINANCE_ALPHA16F,
        gl_LUMINANCE32F, gl_LUMINANCE16F, gl_INTENSITY32F, gl_INTENSITY16F,
        gl_ALPHA32F, gl_ALPHA16F)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_UNSIGNED_NORMALIZED :: GLenum
gl_UNSIGNED_NORMALIZED = 35863
 
gl_TEXTURE_RED_TYPE :: GLenum
gl_TEXTURE_RED_TYPE = 35856
 
gl_TEXTURE_LUMINANCE_TYPE :: GLenum
gl_TEXTURE_LUMINANCE_TYPE = 35860
 
gl_TEXTURE_INTENSITY_TYPE :: GLenum
gl_TEXTURE_INTENSITY_TYPE = 35861
 
gl_TEXTURE_GREEN_TYPE :: GLenum
gl_TEXTURE_GREEN_TYPE = 35857
 
gl_TEXTURE_DEPTH_TYPE :: GLenum
gl_TEXTURE_DEPTH_TYPE = 35862
 
gl_TEXTURE_BLUE_TYPE :: GLenum
gl_TEXTURE_BLUE_TYPE = 35858
 
gl_TEXTURE_ALPHA_TYPE :: GLenum
gl_TEXTURE_ALPHA_TYPE = 35859
 
gl_RGBA32F :: GLenum
gl_RGBA32F = 34836
 
gl_RGBA16F :: GLenum
gl_RGBA16F = 34842
 
gl_RGB32F :: GLenum
gl_RGB32F = 34837
 
gl_RGB16F :: GLenum
gl_RGB16F = 34843
 
gl_LUMINANCE_ALPHA32F :: GLenum
gl_LUMINANCE_ALPHA32F = 34841
 
gl_LUMINANCE_ALPHA16F :: GLenum
gl_LUMINANCE_ALPHA16F = 34847
 
gl_LUMINANCE32F :: GLenum
gl_LUMINANCE32F = 34840
 
gl_LUMINANCE16F :: GLenum
gl_LUMINANCE16F = 34846
 
gl_INTENSITY32F :: GLenum
gl_INTENSITY32F = 34839
 
gl_INTENSITY16F :: GLenum
gl_INTENSITY16F = 34845
 
gl_ALPHA32F :: GLenum
gl_ALPHA32F = 34838
 
gl_ALPHA16F :: GLenum
gl_ALPHA16F = 34844