module Graphics.Rendering.OpenGL.Raw.ARB.VertexProgram
       (glVertexAttribPointer, glVertexAttrib4usv, glVertexAttrib4uiv,
        glVertexAttrib4ubv, glVertexAttrib4sv, glVertexAttrib4s,
        glVertexAttrib4iv, glVertexAttrib4fv, glVertexAttrib4f,
        glVertexAttrib4dv, glVertexAttrib4d, glVertexAttrib4bv,
        glVertexAttrib4Nusv, glVertexAttrib4Nuiv, glVertexAttrib4Nubv,
        glVertexAttrib4Nub, glVertexAttrib4Nsv, glVertexAttrib4Niv,
        glVertexAttrib4Nbv, glVertexAttrib3sv, glVertexAttrib3s,
        glVertexAttrib3fv, glVertexAttrib3f, glVertexAttrib3dv,
        glVertexAttrib3d, glVertexAttrib2sv, glVertexAttrib2s,
        glVertexAttrib2fv, glVertexAttrib2f, glVertexAttrib2dv,
        glVertexAttrib2d, glVertexAttrib1sv, glVertexAttrib1s,
        glVertexAttrib1fv, glVertexAttrib1f, glVertexAttrib1dv,
        glVertexAttrib1d, glProgramString, glProgramLocalParameter4fv,
        glProgramLocalParameter4f, glProgramLocalParameter4dv,
        glProgramLocalParameter4d, glProgramEnvParameter4fv,
        glProgramEnvParameter4f, glProgramEnvParameter4dv,
        glProgramEnvParameter4d, glIsProgram, glGetVertexAttribiv,
        glGetVertexAttribfv, glGetVertexAttribdv,
        glGetVertexAttribPointerv, glGetProgramiv, glGetProgramString,
        glGetProgramLocalParameterfv, glGetProgramLocalParameterdv,
        glGetProgramEnvParameterfv, glGetProgramEnvParameterdv,
        glGenPrograms, glEnableVertexAttribArray,
        glDisableVertexAttribArray, glDeletePrograms, glBindProgram,
        gl_VERTEX_PROGRAM_TWO_SIDE, gl_VERTEX_PROGRAM_POINT_SIZE,
        gl_VERTEX_PROGRAM, gl_VERTEX_ATTRIB_ARRAY_TYPE,
        gl_VERTEX_ATTRIB_ARRAY_STRIDE, gl_VERTEX_ATTRIB_ARRAY_SIZE,
        gl_VERTEX_ATTRIB_ARRAY_POINTER, gl_VERTEX_ATTRIB_ARRAY_NORMALIZED,
        gl_VERTEX_ATTRIB_ARRAY_ENABLED, gl_TRANSPOSE_CURRENT_MATRIX,
        gl_PROGRAM_UNDER_NATIVE_LIMITS, gl_PROGRAM_TEMPORARIES,
        gl_PROGRAM_STRING, gl_PROGRAM_PARAMETERS,
        gl_PROGRAM_NATIVE_TEMPORARIES, gl_PROGRAM_NATIVE_PARAMETERS,
        gl_PROGRAM_NATIVE_INSTRUCTIONS, gl_PROGRAM_NATIVE_ATTRIBS,
        gl_PROGRAM_NATIVE_ADDRESS_REGISTERS, gl_PROGRAM_LENGTH,
        gl_PROGRAM_INSTRUCTIONS, gl_PROGRAM_FORMAT_ASCII,
        gl_PROGRAM_FORMAT, gl_PROGRAM_ERROR_STRING,
        gl_PROGRAM_ERROR_POSITION, gl_PROGRAM_BINDING, gl_PROGRAM_ATTRIBS,
        gl_PROGRAM_ADDRESS_REGISTERS, gl_MAX_VERTEX_ATTRIBS,
        gl_MAX_PROGRAM_TEMPORARIES, gl_MAX_PROGRAM_PARAMETERS,
        gl_MAX_PROGRAM_NATIVE_TEMPORARIES,
        gl_MAX_PROGRAM_NATIVE_PARAMETERS,
        gl_MAX_PROGRAM_NATIVE_INSTRUCTIONS, gl_MAX_PROGRAM_NATIVE_ATTRIBS,
        gl_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS,
        gl_MAX_PROGRAM_MATRIX_STACK_DEPTH, gl_MAX_PROGRAM_MATRICES,
        gl_MAX_PROGRAM_LOCAL_PARAMETERS, gl_MAX_PROGRAM_INSTRUCTIONS,
        gl_MAX_PROGRAM_ENV_PARAMETERS, gl_MAX_PROGRAM_ATTRIBS,
        gl_MAX_PROGRAM_ADDRESS_REGISTERS, gl_MATRIX9, gl_MATRIX8,
        gl_MATRIX7, gl_MATRIX6, gl_MATRIX5, gl_MATRIX4, gl_MATRIX3,
        gl_MATRIX31, gl_MATRIX30, gl_MATRIX2, gl_MATRIX29, gl_MATRIX28,
        gl_MATRIX27, gl_MATRIX26, gl_MATRIX25, gl_MATRIX24, gl_MATRIX23,
        gl_MATRIX22, gl_MATRIX21, gl_MATRIX20, gl_MATRIX1, gl_MATRIX19,
        gl_MATRIX18, gl_MATRIX17, gl_MATRIX16, gl_MATRIX15, gl_MATRIX14,
        gl_MATRIX13, gl_MATRIX12, gl_MATRIX11, gl_MATRIX10, gl_MATRIX0,
        gl_CURRENT_VERTEX_ATTRIB, gl_CURRENT_MATRIX_STACK_DEPTH,
        gl_CURRENT_MATRIX, gl_COLOR_SUM)
       where
import Graphics.Rendering.OpenGL.Raw.ARB.FragmentProgram
       (glVertexAttribPointer, glVertexAttrib4usv, glVertexAttrib4uiv,
        glVertexAttrib4ubv, glVertexAttrib4sv, glVertexAttrib4s,
        glVertexAttrib4iv, glVertexAttrib4fv, glVertexAttrib4f,
        glVertexAttrib4dv, glVertexAttrib4d, glVertexAttrib4bv,
        glVertexAttrib4Nusv, glVertexAttrib4Nuiv, glVertexAttrib4Nubv,
        glVertexAttrib4Nub, glVertexAttrib4Nsv, glVertexAttrib4Niv,
        glVertexAttrib4Nbv, glVertexAttrib3sv, glVertexAttrib3s,
        glVertexAttrib3fv, glVertexAttrib3f, glVertexAttrib3dv,
        glVertexAttrib3d, glVertexAttrib2sv, glVertexAttrib2s,
        glVertexAttrib2fv, glVertexAttrib2f, glVertexAttrib2dv,
        glVertexAttrib2d, glVertexAttrib1sv, glVertexAttrib1s,
        glVertexAttrib1fv, glVertexAttrib1f, glVertexAttrib1dv,
        glVertexAttrib1d, glProgramString, glProgramLocalParameter4fv,
        glProgramLocalParameter4f, glProgramLocalParameter4dv,
        glProgramLocalParameter4d, glProgramEnvParameter4fv,
        glProgramEnvParameter4f, glProgramEnvParameter4dv,
        glProgramEnvParameter4d, glIsProgram, glGetVertexAttribiv,
        glGetVertexAttribfv, glGetVertexAttribdv,
        glGetVertexAttribPointerv, glGetProgramiv, glGetProgramString,
        glGetProgramLocalParameterfv, glGetProgramLocalParameterdv,
        glGetProgramEnvParameterfv, glGetProgramEnvParameterdv,
        glGenPrograms, glEnableVertexAttribArray,
        glDisableVertexAttribArray, glDeletePrograms, glBindProgram,
        gl_VERTEX_PROGRAM_TWO_SIDE, gl_VERTEX_PROGRAM_POINT_SIZE,
        gl_VERTEX_PROGRAM, gl_VERTEX_ATTRIB_ARRAY_TYPE,
        gl_VERTEX_ATTRIB_ARRAY_STRIDE, gl_VERTEX_ATTRIB_ARRAY_SIZE,
        gl_VERTEX_ATTRIB_ARRAY_POINTER, gl_VERTEX_ATTRIB_ARRAY_NORMALIZED,
        gl_VERTEX_ATTRIB_ARRAY_ENABLED, gl_TRANSPOSE_CURRENT_MATRIX,
        gl_PROGRAM_UNDER_NATIVE_LIMITS, gl_PROGRAM_TEMPORARIES,
        gl_PROGRAM_STRING, gl_PROGRAM_PARAMETERS,
        gl_PROGRAM_NATIVE_TEMPORARIES, gl_PROGRAM_NATIVE_PARAMETERS,
        gl_PROGRAM_NATIVE_INSTRUCTIONS, gl_PROGRAM_NATIVE_ATTRIBS,
        gl_PROGRAM_NATIVE_ADDRESS_REGISTERS, gl_PROGRAM_LENGTH,
        gl_PROGRAM_INSTRUCTIONS, gl_PROGRAM_FORMAT_ASCII,
        gl_PROGRAM_FORMAT, gl_PROGRAM_ERROR_STRING,
        gl_PROGRAM_ERROR_POSITION, gl_PROGRAM_BINDING, gl_PROGRAM_ATTRIBS,
        gl_PROGRAM_ADDRESS_REGISTERS, gl_MAX_VERTEX_ATTRIBS,
        gl_MAX_PROGRAM_TEMPORARIES, gl_MAX_PROGRAM_PARAMETERS,
        gl_MAX_PROGRAM_NATIVE_TEMPORARIES,
        gl_MAX_PROGRAM_NATIVE_PARAMETERS,
        gl_MAX_PROGRAM_NATIVE_INSTRUCTIONS, gl_MAX_PROGRAM_NATIVE_ATTRIBS,
        gl_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS,
        gl_MAX_PROGRAM_MATRIX_STACK_DEPTH, gl_MAX_PROGRAM_MATRICES,
        gl_MAX_PROGRAM_LOCAL_PARAMETERS, gl_MAX_PROGRAM_INSTRUCTIONS,
        gl_MAX_PROGRAM_ENV_PARAMETERS, gl_MAX_PROGRAM_ATTRIBS,
        gl_MAX_PROGRAM_ADDRESS_REGISTERS, gl_MATRIX9, gl_MATRIX8,
        gl_MATRIX7, gl_MATRIX6, gl_MATRIX5, gl_MATRIX4, gl_MATRIX3,
        gl_MATRIX31, gl_MATRIX30, gl_MATRIX2, gl_MATRIX29, gl_MATRIX28,
        gl_MATRIX27, gl_MATRIX26, gl_MATRIX25, gl_MATRIX24, gl_MATRIX23,
        gl_MATRIX22, gl_MATRIX21, gl_MATRIX20, gl_MATRIX1, gl_MATRIX19,
        gl_MATRIX18, gl_MATRIX17, gl_MATRIX16, gl_MATRIX15, gl_MATRIX14,
        gl_MATRIX13, gl_MATRIX12, gl_MATRIX11, gl_MATRIX10, gl_MATRIX0,
        gl_CURRENT_VERTEX_ATTRIB, gl_CURRENT_MATRIX_STACK_DEPTH,
        gl_CURRENT_MATRIX, gl_COLOR_SUM)