{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.ARB.TextureFloat
       (gl_UNSIGNED_NORMALIZED_ARB, gl_TEXTURE_RED_TYPE_ARB,
        gl_TEXTURE_LUMINANCE_TYPE_ARB, gl_TEXTURE_INTENSITY_TYPE_ARB,
        gl_TEXTURE_GREEN_TYPE_ARB, gl_TEXTURE_DEPTH_TYPE_ARB,
        gl_TEXTURE_BLUE_TYPE_ARB, gl_TEXTURE_ALPHA_TYPE_ARB,
        gl_RGBA32F_ARB, gl_RGBA16F_ARB, gl_RGB32F_ARB, gl_RGB16F_ARB,
        gl_LUMINANCE_ALPHA32F_ARB, gl_LUMINANCE_ALPHA16F_ARB,
        gl_LUMINANCE32F_ARB, gl_LUMINANCE16F_ARB, gl_INTENSITY32F_ARB,
        gl_INTENSITY16F_ARB, gl_ALPHA32F_ARB, gl_ALPHA16F_ARB)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_UNSIGNED_NORMALIZED_ARB :: GLenum
gl_UNSIGNED_NORMALIZED_ARB = 35863
 
gl_TEXTURE_RED_TYPE_ARB :: GLenum
gl_TEXTURE_RED_TYPE_ARB = 35856
 
gl_TEXTURE_LUMINANCE_TYPE_ARB :: GLenum
gl_TEXTURE_LUMINANCE_TYPE_ARB = 35860
 
gl_TEXTURE_INTENSITY_TYPE_ARB :: GLenum
gl_TEXTURE_INTENSITY_TYPE_ARB = 35861
 
gl_TEXTURE_GREEN_TYPE_ARB :: GLenum
gl_TEXTURE_GREEN_TYPE_ARB = 35857
 
gl_TEXTURE_DEPTH_TYPE_ARB :: GLenum
gl_TEXTURE_DEPTH_TYPE_ARB = 35862
 
gl_TEXTURE_BLUE_TYPE_ARB :: GLenum
gl_TEXTURE_BLUE_TYPE_ARB = 35858
 
gl_TEXTURE_ALPHA_TYPE_ARB :: GLenum
gl_TEXTURE_ALPHA_TYPE_ARB = 35859
 
gl_RGBA32F_ARB :: GLenum
gl_RGBA32F_ARB = 34836
 
gl_RGBA16F_ARB :: GLenum
gl_RGBA16F_ARB = 34842
 
gl_RGB32F_ARB :: GLenum
gl_RGB32F_ARB = 34837
 
gl_RGB16F_ARB :: GLenum
gl_RGB16F_ARB = 34843
 
gl_LUMINANCE_ALPHA32F_ARB :: GLenum
gl_LUMINANCE_ALPHA32F_ARB = 34841
 
gl_LUMINANCE_ALPHA16F_ARB :: GLenum
gl_LUMINANCE_ALPHA16F_ARB = 34847
 
gl_LUMINANCE32F_ARB :: GLenum
gl_LUMINANCE32F_ARB = 34840
 
gl_LUMINANCE16F_ARB :: GLenum
gl_LUMINANCE16F_ARB = 34846
 
gl_INTENSITY32F_ARB :: GLenum
gl_INTENSITY32F_ARB = 34839
 
gl_INTENSITY16F_ARB :: GLenum
gl_INTENSITY16F_ARB = 34845
 
gl_ALPHA32F_ARB :: GLenum
gl_ALPHA32F_ARB = 34838
 
gl_ALPHA16F_ARB :: GLenum
gl_ALPHA16F_ARB = 34844