module Graphics.Rendering.OpenGL.Raw.ARB.ComputeShader
       (glDispatchComputeIndirect, glDispatchCompute,
        gl_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER,
        gl_MAX_COMPUTE_WORK_GROUP_SIZE, gl_MAX_COMPUTE_WORK_GROUP_COUNT,
        gl_MAX_COMPUTE_UNIFORM_COMPONENTS, gl_MAX_COMPUTE_UNIFORM_BLOCKS,
        gl_MAX_COMPUTE_TEXTURE_IMAGE_UNITS,
        gl_MAX_COMPUTE_SHARED_MEMORY_SIZE,
        gl_MAX_COMPUTE_LOCAL_INVOCATIONS, gl_MAX_COMPUTE_IMAGE_UNIFORMS,
        gl_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS,
        gl_MAX_COMPUTE_ATOMIC_COUNTERS,
        gl_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS,
        gl_DISPATCH_INDIRECT_BUFFER_BINDING, gl_DISPATCH_INDIRECT_BUFFER,
        gl_COMPUTE_SHADER_BIT, gl_COMPUTE_SHADER,
        gl_COMPUTE_LOCAL_WORK_SIZE,
        gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER)
       where
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core43
       (glDispatchComputeIndirect, glDispatchCompute,
        gl_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER,
        gl_MAX_COMPUTE_WORK_GROUP_SIZE, gl_MAX_COMPUTE_WORK_GROUP_COUNT,
        gl_MAX_COMPUTE_UNIFORM_COMPONENTS, gl_MAX_COMPUTE_UNIFORM_BLOCKS,
        gl_MAX_COMPUTE_TEXTURE_IMAGE_UNITS,
        gl_MAX_COMPUTE_SHARED_MEMORY_SIZE,
        gl_MAX_COMPUTE_LOCAL_INVOCATIONS, gl_MAX_COMPUTE_IMAGE_UNIFORMS,
        gl_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS,
        gl_MAX_COMPUTE_ATOMIC_COUNTERS,
        gl_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS,
        gl_DISPATCH_INDIRECT_BUFFER_BINDING, gl_DISPATCH_INDIRECT_BUFFER,
        gl_COMPUTE_SHADER, gl_COMPUTE_LOCAL_WORK_SIZE,
        gl_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER)
 
gl_COMPUTE_SHADER_BIT :: GLbitfield
gl_COMPUTE_SHADER_BIT = 32