{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.ARB.ES3Compatibility
       (gl_PRIMITIVE_RESTART_FIXED_INDEX, gl_MAX_ELEMENT_INDEX,
        gl_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
        gl_COMPRESSED_SRGB8_ETC2, gl_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC,
        gl_COMPRESSED_SIGNED_RG11_EAC, gl_COMPRESSED_SIGNED_R11_EAC,
        gl_COMPRESSED_RGBA8_ETC2_EAC,
        gl_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
        gl_COMPRESSED_RGB8_ETC2, gl_COMPRESSED_RG11_EAC,
        gl_COMPRESSED_R11_EAC, gl_ANY_SAMPLES_PASSED_CONSERVATIVE)
       where
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core43
       (gl_PRIMITIVE_RESTART_FIXED_INDEX, gl_MAX_ELEMENT_INDEX,
        gl_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2,
        gl_COMPRESSED_SRGB8_ETC2, gl_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC,
        gl_COMPRESSED_SIGNED_RG11_EAC, gl_COMPRESSED_SIGNED_R11_EAC,
        gl_COMPRESSED_RGBA8_ETC2_EAC,
        gl_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2,
        gl_COMPRESSED_RGB8_ETC2, gl_COMPRESSED_RG11_EAC,
        gl_COMPRESSED_R11_EAC, gl_ANY_SAMPLES_PASSED_CONSERVATIVE)
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions