module Graphics.Rendering.OpenGL.Raw.ARB.SeparateShaderObjects
       (glValidateProgramPipeline, glUseProgramStages,
        glProgramUniformMatrix4x3fv, glProgramUniformMatrix4x3dv,
        glProgramUniformMatrix4x2fv, glProgramUniformMatrix4x2dv,
        glProgramUniformMatrix4fv, glProgramUniformMatrix4dv,
        glProgramUniformMatrix3x4fv, glProgramUniformMatrix3x4dv,
        glProgramUniformMatrix3x2fv, glProgramUniformMatrix3x2dv,
        glProgramUniformMatrix3fv, glProgramUniformMatrix3dv,
        glProgramUniformMatrix2x4fv, glProgramUniformMatrix2x4dv,
        glProgramUniformMatrix2x3fv, glProgramUniformMatrix2x3dv,
        glProgramUniformMatrix2fv, glProgramUniformMatrix2dv,
        glProgramUniform4uiv, glProgramUniform4ui, glProgramUniform4iv,
        glProgramUniform4i, glProgramUniform4fv, glProgramUniform4f,
        glProgramUniform4dv, glProgramUniform4d, glProgramUniform3uiv,
        glProgramUniform3ui, glProgramUniform3iv, glProgramUniform3i,
        glProgramUniform3fv, glProgramUniform3f, glProgramUniform3dv,
        glProgramUniform3d, glProgramUniform2uiv, glProgramUniform2ui,
        glProgramUniform2iv, glProgramUniform2i, glProgramUniform2fv,
        glProgramUniform2f, glProgramUniform2dv, glProgramUniform2d,
        glProgramUniform1uiv, glProgramUniform1ui, glProgramUniform1iv,
        glProgramUniform1i, glProgramUniform1fv, glProgramUniform1f,
        glProgramUniform1dv, glProgramUniform1d, glIsProgramPipeline,
        glGetProgramPipelineiv, glGetProgramPipelineInfoLog,
        glGenProgramPipelines, glDeleteProgramPipelines,
        glCreateShaderProgramv, glBindProgramPipeline,
        glActiveShaderProgram, gl_VERTEX_SHADER_BIT,
        gl_TESS_EVALUATION_SHADER_BIT, gl_TESS_CONTROL_SHADER_BIT,
        gl_PROGRAM_SEPARABLE, gl_PROGRAM_PIPELINE_BINDING,
        gl_GEOMETRY_SHADER_BIT, gl_FRAGMENT_SHADER_BIT, gl_ALL_SHADER_BITS,
        gl_ACTIVE_PROGRAM)
       where
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core41
       (glValidateProgramPipeline, glUseProgramStages,
        glProgramUniformMatrix4x3fv, glProgramUniformMatrix4x3dv,
        glProgramUniformMatrix4x2fv, glProgramUniformMatrix4x2dv,
        glProgramUniformMatrix4fv, glProgramUniformMatrix4dv,
        glProgramUniformMatrix3x4fv, glProgramUniformMatrix3x4dv,
        glProgramUniformMatrix3x2fv, glProgramUniformMatrix3x2dv,
        glProgramUniformMatrix3fv, glProgramUniformMatrix3dv,
        glProgramUniformMatrix2x4fv, glProgramUniformMatrix2x4dv,
        glProgramUniformMatrix2x3fv, glProgramUniformMatrix2x3dv,
        glProgramUniformMatrix2fv, glProgramUniformMatrix2dv,
        glProgramUniform4uiv, glProgramUniform4ui, glProgramUniform4iv,
        glProgramUniform4i, glProgramUniform4fv, glProgramUniform4f,
        glProgramUniform4dv, glProgramUniform4d, glProgramUniform3uiv,
        glProgramUniform3ui, glProgramUniform3iv, glProgramUniform3i,
        glProgramUniform3fv, glProgramUniform3f, glProgramUniform3dv,
        glProgramUniform3d, glProgramUniform2uiv, glProgramUniform2ui,
        glProgramUniform2iv, glProgramUniform2i, glProgramUniform2fv,
        glProgramUniform2f, glProgramUniform2dv, glProgramUniform2d,
        glProgramUniform1uiv, glProgramUniform1ui, glProgramUniform1iv,
        glProgramUniform1i, glProgramUniform1fv, glProgramUniform1f,
        glProgramUniform1dv, glProgramUniform1d, glIsProgramPipeline,
        glGetProgramPipelineiv, glGetProgramPipelineInfoLog,
        glGenProgramPipelines, glDeleteProgramPipelines,
        glCreateShaderProgramv, glBindProgramPipeline,
        glActiveShaderProgram, gl_VERTEX_SHADER_BIT,
        gl_TESS_EVALUATION_SHADER_BIT, gl_TESS_CONTROL_SHADER_BIT,
        gl_PROGRAM_SEPARABLE, gl_PROGRAM_PIPELINE_BINDING,
        gl_GEOMETRY_SHADER_BIT, gl_FRAGMENT_SHADER_BIT, gl_ALL_SHADER_BITS,
        gl_ACTIVE_PROGRAM)