module Graphics.Rendering.OpenGL.Raw.ARB.SeparateShaderObjects
       (glGetProgramPipelineInfoLog, glValidateProgramPipeline,
        glProgramUniformMatrix4x3dv, glProgramUniformMatrix3x4dv,
        glProgramUniformMatrix4x2dv, glProgramUniformMatrix2x4dv,
        glProgramUniformMatrix3x2dv, glProgramUniformMatrix2x3dv,
        glProgramUniformMatrix4x3fv, glProgramUniformMatrix3x4fv,
        glProgramUniformMatrix4x2fv, glProgramUniformMatrix2x4fv,
        glProgramUniformMatrix3x2fv, glProgramUniformMatrix2x3fv,
        glProgramUniformMatrix4dv, glProgramUniformMatrix3dv,
        glProgramUniformMatrix2dv, glProgramUniformMatrix4fv,
        glProgramUniformMatrix3fv, glProgramUniformMatrix2fv,
        glProgramUniform4uiv, glProgramUniform4ui, glProgramUniform4dv,
        glProgramUniform4d, glProgramUniform4fv, glProgramUniform4f,
        glProgramUniform4iv, glProgramUniform4i, glProgramUniform3uiv,
        glProgramUniform3ui, glProgramUniform3dv, glProgramUniform3d,
        glProgramUniform3fv, glProgramUniform3f, glProgramUniform3iv,
        glProgramUniform3i, glProgramUniform2uiv, glProgramUniform2ui,
        glProgramUniform2dv, glProgramUniform2d, glProgramUniform2fv,
        glProgramUniform2f, glProgramUniform2iv, glProgramUniform2i,
        glProgramUniform1uiv, glProgramUniform1ui, glProgramUniform1dv,
        glProgramUniform1d, glProgramUniform1fv, glProgramUniform1f,
        glProgramUniform1iv, glProgramUniform1i, glGetProgramPipelineiv,
        glIsProgramPipeline, glGenProgramPipelines,
        glDeleteProgramPipelines, glBindProgramPipeline,
        glCreateShaderProgramv, glActiveShaderProgram, glUseProgramStages,
        gl_PROGRAM_PIPELINE_BINDING, gl_ACTIVE_PROGRAM,
        gl_PROGRAM_SEPARABLE, gl_ALL_SHADER_BITS,
        gl_TESS_EVALUATION_SHADER_BIT, gl_TESS_CONTROL_SHADER_BIT,
        gl_GEOMETRY_SHADER_BIT, gl_FRAGMENT_SHADER_BIT,
        gl_VERTEX_SHADER_BIT)
       where
import Graphics.Rendering.OpenGL.Raw.Core.Internal.Core41
       (glGetProgramPipelineInfoLog, glValidateProgramPipeline,
        glProgramUniformMatrix4x3dv, glProgramUniformMatrix3x4dv,
        glProgramUniformMatrix4x2dv, glProgramUniformMatrix2x4dv,
        glProgramUniformMatrix3x2dv, glProgramUniformMatrix2x3dv,
        glProgramUniformMatrix4x3fv, glProgramUniformMatrix3x4fv,
        glProgramUniformMatrix4x2fv, glProgramUniformMatrix2x4fv,
        glProgramUniformMatrix3x2fv, glProgramUniformMatrix2x3fv,
        glProgramUniformMatrix4dv, glProgramUniformMatrix3dv,
        glProgramUniformMatrix2dv, glProgramUniformMatrix4fv,
        glProgramUniformMatrix3fv, glProgramUniformMatrix2fv,
        glProgramUniform4uiv, glProgramUniform4ui, glProgramUniform4dv,
        glProgramUniform4d, glProgramUniform4fv, glProgramUniform4f,
        glProgramUniform4iv, glProgramUniform4i, glProgramUniform3uiv,
        glProgramUniform3ui, glProgramUniform3dv, glProgramUniform3d,
        glProgramUniform3fv, glProgramUniform3f, glProgramUniform3iv,
        glProgramUniform3i, glProgramUniform2uiv, glProgramUniform2ui,
        glProgramUniform2dv, glProgramUniform2d, glProgramUniform2fv,
        glProgramUniform2f, glProgramUniform2iv, glProgramUniform2i,
        glProgramUniform1uiv, glProgramUniform1ui, glProgramUniform1dv,
        glProgramUniform1d, glProgramUniform1fv, glProgramUniform1f,
        glProgramUniform1iv, glProgramUniform1i, glGetProgramPipelineiv,
        glIsProgramPipeline, glGenProgramPipelines,
        glDeleteProgramPipelines, glBindProgramPipeline,
        glCreateShaderProgramv, glActiveShaderProgram, glUseProgramStages,
        gl_PROGRAM_PIPELINE_BINDING, gl_ACTIVE_PROGRAM,
        gl_PROGRAM_SEPARABLE, gl_ALL_SHADER_BITS,
        gl_TESS_EVALUATION_SHADER_BIT, gl_TESS_CONTROL_SHADER_BIT,
        gl_GEOMETRY_SHADER_BIT, gl_FRAGMENT_SHADER_BIT,
        gl_VERTEX_SHADER_BIT)