{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.ARB.TextureCubeMap
       (gl_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB,
        gl_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB,
        gl_TEXTURE_CUBE_MAP_POSITIVE_X_ARB,
        gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB,
        gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB,
        gl_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB, gl_TEXTURE_CUBE_MAP_ARB,
        gl_TEXTURE_BINDING_CUBE_MAP_ARB, gl_REFLECTION_MAP_ARB,
        gl_PROXY_TEXTURE_CUBE_MAP_ARB, gl_NORMAL_MAP_ARB,
        gl_MAX_CUBE_MAP_TEXTURE_SIZE_ARB)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_Z_ARB = 34073
 
gl_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_Y_ARB = 34071
 
gl_TEXTURE_CUBE_MAP_POSITIVE_X_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_X_ARB = 34069
 
gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_ARB = 34074
 
gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_ARB = 34072
 
gl_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_X_ARB = 34070
 
gl_TEXTURE_CUBE_MAP_ARB :: GLenum
gl_TEXTURE_CUBE_MAP_ARB = 34067
 
gl_TEXTURE_BINDING_CUBE_MAP_ARB :: GLenum
gl_TEXTURE_BINDING_CUBE_MAP_ARB = 34068
 
gl_REFLECTION_MAP_ARB :: GLenum
gl_REFLECTION_MAP_ARB = 34066
 
gl_PROXY_TEXTURE_CUBE_MAP_ARB :: GLenum
gl_PROXY_TEXTURE_CUBE_MAP_ARB = 34075
 
gl_NORMAL_MAP_ARB :: GLenum
gl_NORMAL_MAP_ARB = 34065
 
gl_MAX_CUBE_MAP_TEXTURE_SIZE_ARB :: GLenum
gl_MAX_CUBE_MAP_TEXTURE_SIZE_ARB = 34076