{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.ARB.TextureGather
       (gl_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB,
        gl_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB,
        gl_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB :: GLenum
gl_MIN_PROGRAM_TEXTURE_GATHER_OFFSET_ARB = 36446
 
gl_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB :: GLenum
gl_MAX_PROGRAM_TEXTURE_GATHER_OFFSET_ARB = 36447
 
gl_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB :: GLenum
gl_MAX_PROGRAM_TEXTURE_GATHER_COMPONENTS_ARB = 36767