module Graphics.Rendering.OpenGL.Raw.ARB.VertexProgram
       (glIsProgramARB, glGetVertexAttribPointervARB,
        glGetVertexAttribivARB, glGetVertexAttribfvARB,
        glGetVertexAttribdvARB, glGetProgramStringARB, glGetProgramivARB,
        glGetProgramLocalParameterfvARB, glGetProgramLocalParameterdvARB,
        glGetProgramEnvParameterfvARB, glGetProgramEnvParameterdvARB,
        glProgramLocalParameter4fvARB, glProgramLocalParameter4fARB,
        glProgramLocalParameter4dvARB, glProgramLocalParameter4dARB,
        glProgramEnvParameter4fvARB, glProgramEnvParameter4fARB,
        glProgramEnvParameter4dvARB, glProgramEnvParameter4dARB,
        glGenProgramsARB, glDeleteProgramsARB, glBindProgramARB,
        glProgramStringARB, glDisableVertexAttribArrayARB,
        glEnableVertexAttribArrayARB, glVertexAttribPointerARB,
        glVertexAttrib4usvARB, glVertexAttrib4uivARB,
        glVertexAttrib4ubvARB, glVertexAttrib4svARB, glVertexAttrib4sARB,
        glVertexAttrib4ivARB, glVertexAttrib4fvARB, glVertexAttrib4fARB,
        glVertexAttrib4dvARB, glVertexAttrib4dARB, glVertexAttrib4bvARB,
        glVertexAttrib4NusvARB, glVertexAttrib4NuivARB,
        glVertexAttrib4NubvARB, glVertexAttrib4NubARB,
        glVertexAttrib4NsvARB, glVertexAttrib4NivARB,
        glVertexAttrib4NbvARB, glVertexAttrib3svARB, glVertexAttrib3sARB,
        glVertexAttrib3fvARB, glVertexAttrib3fARB, glVertexAttrib3dvARB,
        glVertexAttrib3dARB, glVertexAttrib2svARB, glVertexAttrib2sARB,
        glVertexAttrib2fvARB, glVertexAttrib2fARB, glVertexAttrib2dvARB,
        glVertexAttrib2dARB, glVertexAttrib1svARB, glVertexAttrib1sARB,
        glVertexAttrib1fvARB, glVertexAttrib1fARB, glVertexAttrib1dvARB,
        glVertexAttrib1dARB, gl_MATRIX31_ARB, gl_MATRIX30_ARB,
        gl_MATRIX29_ARB, gl_MATRIX28_ARB, gl_MATRIX27_ARB, gl_MATRIX26_ARB,
        gl_MATRIX25_ARB, gl_MATRIX24_ARB, gl_MATRIX23_ARB, gl_MATRIX22_ARB,
        gl_MATRIX21_ARB, gl_MATRIX20_ARB, gl_MATRIX19_ARB, gl_MATRIX18_ARB,
        gl_MATRIX17_ARB, gl_MATRIX16_ARB, gl_MATRIX15_ARB, gl_MATRIX14_ARB,
        gl_MATRIX13_ARB, gl_MATRIX12_ARB, gl_MATRIX11_ARB, gl_MATRIX10_ARB,
        gl_MATRIX9_ARB, gl_MATRIX8_ARB, gl_MATRIX7_ARB, gl_MATRIX6_ARB,
        gl_MATRIX5_ARB, gl_MATRIX4_ARB, gl_MATRIX3_ARB, gl_MATRIX2_ARB,
        gl_MATRIX1_ARB, gl_MATRIX0_ARB, gl_TRANSPOSE_CURRENT_MATRIX_ARB,
        gl_PROGRAM_UNDER_NATIVE_LIMITS_ARB,
        gl_MAX_PROGRAM_ENV_PARAMETERS_ARB,
        gl_MAX_PROGRAM_LOCAL_PARAMETERS_ARB,
        gl_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB,
        gl_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB,
        gl_MAX_PROGRAM_ADDRESS_REGISTERS_ARB,
        gl_PROGRAM_ADDRESS_REGISTERS_ARB,
        gl_MAX_PROGRAM_NATIVE_ATTRIBS_ARB, gl_PROGRAM_NATIVE_ATTRIBS_ARB,
        gl_MAX_PROGRAM_ATTRIBS_ARB, gl_PROGRAM_ATTRIBS_ARB,
        gl_MAX_PROGRAM_NATIVE_PARAMETERS_ARB,
        gl_PROGRAM_NATIVE_PARAMETERS_ARB, gl_MAX_PROGRAM_PARAMETERS_ARB,
        gl_PROGRAM_PARAMETERS_ARB, gl_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB,
        gl_PROGRAM_NATIVE_TEMPORARIES_ARB, gl_MAX_PROGRAM_TEMPORARIES_ARB,
        gl_PROGRAM_TEMPORARIES_ARB, gl_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB,
        gl_PROGRAM_NATIVE_INSTRUCTIONS_ARB,
        gl_MAX_PROGRAM_INSTRUCTIONS_ARB, gl_PROGRAM_INSTRUCTIONS_ARB,
        gl_PROGRAM_FORMAT_ARB, gl_PROGRAM_FORMAT_ASCII_ARB,
        gl_PROGRAM_ERROR_STRING_ARB, gl_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,
        gl_MAX_VERTEX_ATTRIBS_ARB, gl_PROGRAM_BINDING_ARB,
        gl_PROGRAM_ERROR_POSITION_ARB, gl_VERTEX_ATTRIB_ARRAY_POINTER_ARB,
        gl_VERTEX_PROGRAM_TWO_SIDE_ARB, gl_VERTEX_PROGRAM_POINT_SIZE_ARB,
        gl_CURRENT_MATRIX_ARB, gl_CURRENT_MATRIX_STACK_DEPTH_ARB,
        gl_MAX_PROGRAM_MATRICES_ARB, gl_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB,
        gl_PROGRAM_STRING_ARB, gl_PROGRAM_LENGTH_ARB,
        gl_CURRENT_VERTEX_ATTRIB_ARB, gl_VERTEX_ATTRIB_ARRAY_TYPE_ARB,
        gl_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, gl_VERTEX_ATTRIB_ARRAY_SIZE_ARB,
        gl_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, gl_VERTEX_PROGRAM_ARB,
        gl_COLOR_SUM_ARB)
       where
import Graphics.Rendering.OpenGL.Raw.ARB.FragmentProgram
       (glIsProgramARB, glGetVertexAttribPointervARB,
        glGetVertexAttribivARB, glGetVertexAttribfvARB,
        glGetVertexAttribdvARB, glGetProgramStringARB, glGetProgramivARB,
        glGetProgramLocalParameterfvARB, glGetProgramLocalParameterdvARB,
        glGetProgramEnvParameterfvARB, glGetProgramEnvParameterdvARB,
        glProgramLocalParameter4fvARB, glProgramLocalParameter4fARB,
        glProgramLocalParameter4dvARB, glProgramLocalParameter4dARB,
        glProgramEnvParameter4fvARB, glProgramEnvParameter4fARB,
        glProgramEnvParameter4dvARB, glProgramEnvParameter4dARB,
        glGenProgramsARB, glDeleteProgramsARB, glBindProgramARB,
        glProgramStringARB, glDisableVertexAttribArrayARB,
        glEnableVertexAttribArrayARB, glVertexAttribPointerARB,
        glVertexAttrib4usvARB, glVertexAttrib4uivARB,
        glVertexAttrib4ubvARB, glVertexAttrib4svARB, glVertexAttrib4sARB,
        glVertexAttrib4ivARB, glVertexAttrib4fvARB, glVertexAttrib4fARB,
        glVertexAttrib4dvARB, glVertexAttrib4dARB, glVertexAttrib4bvARB,
        glVertexAttrib4NusvARB, glVertexAttrib4NuivARB,
        glVertexAttrib4NubvARB, glVertexAttrib4NubARB,
        glVertexAttrib4NsvARB, glVertexAttrib4NivARB,
        glVertexAttrib4NbvARB, glVertexAttrib3svARB, glVertexAttrib3sARB,
        glVertexAttrib3fvARB, glVertexAttrib3fARB, glVertexAttrib3dvARB,
        glVertexAttrib3dARB, glVertexAttrib2svARB, glVertexAttrib2sARB,
        glVertexAttrib2fvARB, glVertexAttrib2fARB, glVertexAttrib2dvARB,
        glVertexAttrib2dARB, glVertexAttrib1svARB, glVertexAttrib1sARB,
        glVertexAttrib1fvARB, glVertexAttrib1fARB, glVertexAttrib1dvARB,
        glVertexAttrib1dARB, gl_MATRIX31_ARB, gl_MATRIX30_ARB,
        gl_MATRIX29_ARB, gl_MATRIX28_ARB, gl_MATRIX27_ARB, gl_MATRIX26_ARB,
        gl_MATRIX25_ARB, gl_MATRIX24_ARB, gl_MATRIX23_ARB, gl_MATRIX22_ARB,
        gl_MATRIX21_ARB, gl_MATRIX20_ARB, gl_MATRIX19_ARB, gl_MATRIX18_ARB,
        gl_MATRIX17_ARB, gl_MATRIX16_ARB, gl_MATRIX15_ARB, gl_MATRIX14_ARB,
        gl_MATRIX13_ARB, gl_MATRIX12_ARB, gl_MATRIX11_ARB, gl_MATRIX10_ARB,
        gl_MATRIX9_ARB, gl_MATRIX8_ARB, gl_MATRIX7_ARB, gl_MATRIX6_ARB,
        gl_MATRIX5_ARB, gl_MATRIX4_ARB, gl_MATRIX3_ARB, gl_MATRIX2_ARB,
        gl_MATRIX1_ARB, gl_MATRIX0_ARB, gl_TRANSPOSE_CURRENT_MATRIX_ARB,
        gl_PROGRAM_UNDER_NATIVE_LIMITS_ARB,
        gl_MAX_PROGRAM_ENV_PARAMETERS_ARB,
        gl_MAX_PROGRAM_LOCAL_PARAMETERS_ARB,
        gl_MAX_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB,
        gl_PROGRAM_NATIVE_ADDRESS_REGISTERS_ARB,
        gl_MAX_PROGRAM_ADDRESS_REGISTERS_ARB,
        gl_PROGRAM_ADDRESS_REGISTERS_ARB,
        gl_MAX_PROGRAM_NATIVE_ATTRIBS_ARB, gl_PROGRAM_NATIVE_ATTRIBS_ARB,
        gl_MAX_PROGRAM_ATTRIBS_ARB, gl_PROGRAM_ATTRIBS_ARB,
        gl_MAX_PROGRAM_NATIVE_PARAMETERS_ARB,
        gl_PROGRAM_NATIVE_PARAMETERS_ARB, gl_MAX_PROGRAM_PARAMETERS_ARB,
        gl_PROGRAM_PARAMETERS_ARB, gl_MAX_PROGRAM_NATIVE_TEMPORARIES_ARB,
        gl_PROGRAM_NATIVE_TEMPORARIES_ARB, gl_MAX_PROGRAM_TEMPORARIES_ARB,
        gl_PROGRAM_TEMPORARIES_ARB, gl_MAX_PROGRAM_NATIVE_INSTRUCTIONS_ARB,
        gl_PROGRAM_NATIVE_INSTRUCTIONS_ARB,
        gl_MAX_PROGRAM_INSTRUCTIONS_ARB, gl_PROGRAM_INSTRUCTIONS_ARB,
        gl_PROGRAM_FORMAT_ARB, gl_PROGRAM_FORMAT_ASCII_ARB,
        gl_PROGRAM_ERROR_STRING_ARB, gl_VERTEX_ATTRIB_ARRAY_NORMALIZED_ARB,
        gl_MAX_VERTEX_ATTRIBS_ARB, gl_PROGRAM_BINDING_ARB,
        gl_PROGRAM_ERROR_POSITION_ARB, gl_VERTEX_ATTRIB_ARRAY_POINTER_ARB,
        gl_VERTEX_PROGRAM_TWO_SIDE_ARB, gl_VERTEX_PROGRAM_POINT_SIZE_ARB,
        gl_CURRENT_MATRIX_ARB, gl_CURRENT_MATRIX_STACK_DEPTH_ARB,
        gl_MAX_PROGRAM_MATRICES_ARB, gl_MAX_PROGRAM_MATRIX_STACK_DEPTH_ARB,
        gl_PROGRAM_STRING_ARB, gl_PROGRAM_LENGTH_ARB,
        gl_CURRENT_VERTEX_ATTRIB_ARB, gl_VERTEX_ATTRIB_ARRAY_TYPE_ARB,
        gl_VERTEX_ATTRIB_ARRAY_STRIDE_ARB, gl_VERTEX_ATTRIB_ARRAY_SIZE_ARB,
        gl_VERTEX_ATTRIB_ARRAY_ENABLED_ARB, gl_VERTEX_PROGRAM_ARB,
        gl_COLOR_SUM_ARB)