{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.TextureCompressionLatc
       (gl_COMPRESSED_SIGNED_LUMINANCE_LATC1,
        gl_COMPRESSED_SIGNED_LUMINANCE_ALPHA_LATC2,
        gl_COMPRESSED_LUMINANCE_LATC1, gl_COMPRESSED_LUMINANCE_ALPHA_LATC2)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_COMPRESSED_SIGNED_LUMINANCE_LATC1 :: GLenum
gl_COMPRESSED_SIGNED_LUMINANCE_LATC1 = 35953
 
gl_COMPRESSED_SIGNED_LUMINANCE_ALPHA_LATC2 :: GLenum
gl_COMPRESSED_SIGNED_LUMINANCE_ALPHA_LATC2 = 35955
 
gl_COMPRESSED_LUMINANCE_LATC1 :: GLenum
gl_COMPRESSED_LUMINANCE_LATC1 = 35952
 
gl_COMPRESSED_LUMINANCE_ALPHA_LATC2 :: GLenum
gl_COMPRESSED_LUMINANCE_ALPHA_LATC2 = 35954