{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.TextureSRGB
       (gl_SRGB, gl_SRGB_ALPHA, gl_SRGB8, gl_SRGB8_ALPHA8, gl_SLUMINANCE,
        gl_SLUMINANCE_ALPHA, gl_SLUMINANCE8, gl_SLUMINANCE8_ALPHA8,
        gl_COMPRESSED_SRGB_S3TC_DXT1, gl_COMPRESSED_SRGB,
        gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5,
        gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3,
        gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1, gl_COMPRESSED_SRGB_ALPHA,
        gl_COMPRESSED_SLUMINANCE, gl_COMPRESSED_SLUMINANCE_ALPHA)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_SRGB :: GLenum
gl_SRGB = 35904
 
gl_SRGB_ALPHA :: GLenum
gl_SRGB_ALPHA = 35906
 
gl_SRGB8 :: GLenum
gl_SRGB8 = 35905
 
gl_SRGB8_ALPHA8 :: GLenum
gl_SRGB8_ALPHA8 = 35907
 
gl_SLUMINANCE :: GLenum
gl_SLUMINANCE = 35910
 
gl_SLUMINANCE_ALPHA :: GLenum
gl_SLUMINANCE_ALPHA = 35908
 
gl_SLUMINANCE8 :: GLenum
gl_SLUMINANCE8 = 35911
 
gl_SLUMINANCE8_ALPHA8 :: GLenum
gl_SLUMINANCE8_ALPHA8 = 35909
 
gl_COMPRESSED_SRGB_S3TC_DXT1 :: GLenum
gl_COMPRESSED_SRGB_S3TC_DXT1 = 35916
 
gl_COMPRESSED_SRGB :: GLenum
gl_COMPRESSED_SRGB = 35912
 
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5 :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5 = 35919
 
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3 :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3 = 35918
 
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1 :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1 = 35917
 
gl_COMPRESSED_SRGB_ALPHA :: GLenum
gl_COMPRESSED_SRGB_ALPHA = 35913
 
gl_COMPRESSED_SLUMINANCE :: GLenum
gl_COMPRESSED_SLUMINANCE = 35914
 
gl_COMPRESSED_SLUMINANCE_ALPHA :: GLenum
gl_COMPRESSED_SLUMINANCE_ALPHA = 35915