{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.GeometryShader4
       (glProgramParameteriEXT, gl_TRIANGLE_STRIP_ADJACENCY_EXT,
        gl_TRIANGLES_ADJACENCY_EXT, gl_PROGRAM_POINT_SIZE_EXT,
        gl_MAX_VERTEX_VARYING_COMPONENTS_EXT,
        gl_MAX_VARYING_COMPONENTS_EXT,
        gl_MAX_GEOMETRY_VARYING_COMPONENTS_EXT,
        gl_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT,
        gl_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT,
        gl_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT,
        gl_MAX_GEOMETRY_OUTPUT_VERTICES_EXT, gl_LINE_STRIP_ADJACENCY_EXT,
        gl_LINES_ADJACENCY_EXT, gl_GEOMETRY_VERTICES_OUT_EXT,
        gl_GEOMETRY_SHADER_EXT, gl_GEOMETRY_OUTPUT_TYPE_EXT,
        gl_GEOMETRY_INPUT_TYPE_EXT,
        gl_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT,
        gl_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT,
        gl_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT,
        gl_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
{-# NOINLINE ptr_glProgramParameteriEXT #-}
 
ptr_glProgramParameteriEXT :: FunPtr a
ptr_glProgramParameteriEXT
  = unsafePerformIO $
      Graphics.Rendering.OpenGL.Raw.Internal.Extensions.getExtensionEntry
        "GL_EXT_geometry_shader4"
        "glProgramParameteriEXT"
 
glProgramParameteriEXT :: GLuint -> GLenum -> GLint -> IO ()
glProgramParameteriEXT
  = dyn_glProgramParameteriEXT ptr_glProgramParameteriEXT
 
foreign import CALLCONV unsafe "dynamic" dyn_glProgramParameteriEXT
               ::
               Graphics.Rendering.OpenGL.Raw.Internal.Extensions.Invoker
                 (GLuint -> GLenum -> GLint -> IO ())
 
gl_TRIANGLE_STRIP_ADJACENCY_EXT :: GLenum
gl_TRIANGLE_STRIP_ADJACENCY_EXT = 13
 
gl_TRIANGLES_ADJACENCY_EXT :: GLenum
gl_TRIANGLES_ADJACENCY_EXT = 12
 
gl_PROGRAM_POINT_SIZE_EXT :: GLenum
gl_PROGRAM_POINT_SIZE_EXT = 34370
 
gl_MAX_VERTEX_VARYING_COMPONENTS_EXT :: GLenum
gl_MAX_VERTEX_VARYING_COMPONENTS_EXT = 36318
 
gl_MAX_VARYING_COMPONENTS_EXT :: GLenum
gl_MAX_VARYING_COMPONENTS_EXT = 35659
 
gl_MAX_GEOMETRY_VARYING_COMPONENTS_EXT :: GLenum
gl_MAX_GEOMETRY_VARYING_COMPONENTS_EXT = 36317
 
gl_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT :: GLenum
gl_MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT = 36319
 
gl_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT :: GLenum
gl_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT = 36321
 
gl_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT :: GLenum
gl_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT = 35881
 
gl_MAX_GEOMETRY_OUTPUT_VERTICES_EXT :: GLenum
gl_MAX_GEOMETRY_OUTPUT_VERTICES_EXT = 36320
 
gl_LINE_STRIP_ADJACENCY_EXT :: GLenum
gl_LINE_STRIP_ADJACENCY_EXT = 11
 
gl_LINES_ADJACENCY_EXT :: GLenum
gl_LINES_ADJACENCY_EXT = 10
 
gl_GEOMETRY_VERTICES_OUT_EXT :: GLenum
gl_GEOMETRY_VERTICES_OUT_EXT = 36314
 
gl_GEOMETRY_SHADER_EXT :: GLenum
gl_GEOMETRY_SHADER_EXT = 36313
 
gl_GEOMETRY_OUTPUT_TYPE_EXT :: GLenum
gl_GEOMETRY_OUTPUT_TYPE_EXT = 36316
 
gl_GEOMETRY_INPUT_TYPE_EXT :: GLenum
gl_GEOMETRY_INPUT_TYPE_EXT = 36315
 
gl_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT :: GLenum
gl_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT = 36264
 
gl_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT :: GLenum
gl_FRAMEBUFFER_INCOMPLETE_LAYER_COUNT_EXT = 36265
 
gl_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT :: GLenum
gl_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER_EXT = 36052
 
gl_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT :: GLenum
gl_FRAMEBUFFER_ATTACHMENT_LAYERED_EXT = 36263