{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.ShaderImageLoadStore
       (glMemoryBarrierEXT, glBindImageTextureEXT,
        gl_ALL_BARRIER_BITS_EXT, gl_ATOMIC_COUNTER_BARRIER_BIT_EXT,
        gl_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT,
        gl_FRAMEBUFFER_BARRIER_BIT_EXT, gl_BUFFER_UPDATE_BARRIER_BIT_EXT,
        gl_TEXTURE_UPDATE_BARRIER_BIT_EXT, gl_PIXEL_BUFFER_BARRIER_BIT_EXT,
        gl_COMMAND_BARRIER_BIT_EXT, gl_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT,
        gl_TEXTURE_FETCH_BARRIER_BIT_EXT, gl_UNIFORM_BARRIER_BIT_EXT,
        gl_ELEMENT_ARRAY_BARRIER_BIT_EXT,
        gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT,
        gl_IMAGE_BINDING_FORMAT_EXT, gl_MAX_IMAGE_SAMPLES_EXT,
        gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT,
        gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT,
        gl_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT,
        gl_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT,
        gl_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT,
        gl_UNSIGNED_INT_IMAGE_BUFFER_EXT, gl_UNSIGNED_INT_IMAGE_CUBE_EXT,
        gl_UNSIGNED_INT_IMAGE_2D_RECT_EXT, gl_UNSIGNED_INT_IMAGE_3D_EXT,
        gl_UNSIGNED_INT_IMAGE_2D_EXT, gl_UNSIGNED_INT_IMAGE_1D_EXT,
        gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT,
        gl_INT_IMAGE_2D_MULTISAMPLE_EXT, gl_INT_IMAGE_CUBE_MAP_ARRAY_EXT,
        gl_INT_IMAGE_2D_ARRAY_EXT, gl_INT_IMAGE_1D_ARRAY_EXT,
        gl_INT_IMAGE_BUFFER_EXT, gl_INT_IMAGE_CUBE_EXT,
        gl_INT_IMAGE_2D_RECT_EXT, gl_INT_IMAGE_3D_EXT, gl_INT_IMAGE_2D_EXT,
        gl_INT_IMAGE_1D_EXT, gl_IMAGE_2D_MULTISAMPLE_ARRAY_EXT,
        gl_IMAGE_2D_MULTISAMPLE_EXT, gl_IMAGE_CUBE_MAP_ARRAY_EXT,
        gl_IMAGE_2D_ARRAY_EXT, gl_IMAGE_1D_ARRAY_EXT, gl_IMAGE_BUFFER_EXT,
        gl_IMAGE_CUBE_EXT, gl_IMAGE_2D_RECT_EXT, gl_IMAGE_3D_EXT,
        gl_IMAGE_2D_EXT, gl_IMAGE_1D_EXT, gl_IMAGE_BINDING_ACCESS_EXT,
        gl_IMAGE_BINDING_LAYER_EXT, gl_IMAGE_BINDING_LAYERED_EXT,
        gl_IMAGE_BINDING_LEVEL_EXT, gl_IMAGE_BINDING_NAME_EXT,
        gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT,
        gl_MAX_IMAGE_UNITS_EXT)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
{-# NOINLINE ptr_glMemoryBarrierEXT #-}
 
ptr_glMemoryBarrierEXT :: FunPtr a
ptr_glMemoryBarrierEXT
  = unsafePerformIO $
      Graphics.Rendering.OpenGL.Raw.Internal.Extensions.getExtensionEntry
        "GL_EXT_shader_image_load_store"
        "glMemoryBarrierEXT"
 
glMemoryBarrierEXT :: GLbitfield -> IO ()
glMemoryBarrierEXT = dyn_glMemoryBarrierEXT ptr_glMemoryBarrierEXT
 
foreign import CALLCONV unsafe "dynamic" dyn_glMemoryBarrierEXT ::
               Graphics.Rendering.OpenGL.Raw.Internal.Extensions.Invoker
                 (GLbitfield -> IO ())
 
{-# NOINLINE ptr_glBindImageTextureEXT #-}
 
ptr_glBindImageTextureEXT :: FunPtr a
ptr_glBindImageTextureEXT
  = unsafePerformIO $
      Graphics.Rendering.OpenGL.Raw.Internal.Extensions.getExtensionEntry
        "GL_EXT_shader_image_load_store"
        "glBindImageTextureEXT"
 
glBindImageTextureEXT ::
                      GLuint ->
                        GLuint -> GLint -> GLboolean -> GLint -> GLenum -> GLint -> IO ()
glBindImageTextureEXT
  = dyn_glBindImageTextureEXT ptr_glBindImageTextureEXT
 
foreign import CALLCONV unsafe "dynamic" dyn_glBindImageTextureEXT
               ::
               Graphics.Rendering.OpenGL.Raw.Internal.Extensions.Invoker
                 (GLuint ->
                    GLuint -> GLint -> GLboolean -> GLint -> GLenum -> GLint -> IO ())
 
gl_ALL_BARRIER_BITS_EXT :: GLbitfield
gl_ALL_BARRIER_BITS_EXT = 4294967295
 
gl_ATOMIC_COUNTER_BARRIER_BIT_EXT :: GLbitfield
gl_ATOMIC_COUNTER_BARRIER_BIT_EXT = 4096
 
gl_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT :: GLbitfield
gl_TRANSFORM_FEEDBACK_BARRIER_BIT_EXT = 2048
 
gl_FRAMEBUFFER_BARRIER_BIT_EXT :: GLbitfield
gl_FRAMEBUFFER_BARRIER_BIT_EXT = 1024
 
gl_BUFFER_UPDATE_BARRIER_BIT_EXT :: GLbitfield
gl_BUFFER_UPDATE_BARRIER_BIT_EXT = 512
 
gl_TEXTURE_UPDATE_BARRIER_BIT_EXT :: GLbitfield
gl_TEXTURE_UPDATE_BARRIER_BIT_EXT = 256
 
gl_PIXEL_BUFFER_BARRIER_BIT_EXT :: GLbitfield
gl_PIXEL_BUFFER_BARRIER_BIT_EXT = 128
 
gl_COMMAND_BARRIER_BIT_EXT :: GLbitfield
gl_COMMAND_BARRIER_BIT_EXT = 64
 
gl_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT :: GLbitfield
gl_SHADER_IMAGE_ACCESS_BARRIER_BIT_EXT = 32
 
gl_TEXTURE_FETCH_BARRIER_BIT_EXT :: GLbitfield
gl_TEXTURE_FETCH_BARRIER_BIT_EXT = 8
 
gl_UNIFORM_BARRIER_BIT_EXT :: GLbitfield
gl_UNIFORM_BARRIER_BIT_EXT = 4
 
gl_ELEMENT_ARRAY_BARRIER_BIT_EXT :: GLbitfield
gl_ELEMENT_ARRAY_BARRIER_BIT_EXT = 2
 
gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT :: GLbitfield
gl_VERTEX_ATTRIB_ARRAY_BARRIER_BIT_EXT = 1
 
gl_IMAGE_BINDING_FORMAT_EXT :: GLenum
gl_IMAGE_BINDING_FORMAT_EXT = 36974
 
gl_MAX_IMAGE_SAMPLES_EXT :: GLenum
gl_MAX_IMAGE_SAMPLES_EXT = 36973
 
gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT = 36972
 
gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_MULTISAMPLE_EXT = 36971
 
gl_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_CUBE_MAP_ARRAY_EXT = 36970
 
gl_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_ARRAY_EXT = 36969
 
gl_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_1D_ARRAY_EXT = 36968
 
gl_UNSIGNED_INT_IMAGE_BUFFER_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_BUFFER_EXT = 36967
 
gl_UNSIGNED_INT_IMAGE_CUBE_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_CUBE_EXT = 36966
 
gl_UNSIGNED_INT_IMAGE_2D_RECT_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_RECT_EXT = 36965
 
gl_UNSIGNED_INT_IMAGE_3D_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_3D_EXT = 36964
 
gl_UNSIGNED_INT_IMAGE_2D_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_2D_EXT = 36963
 
gl_UNSIGNED_INT_IMAGE_1D_EXT :: GLenum
gl_UNSIGNED_INT_IMAGE_1D_EXT = 36962
 
gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT :: GLenum
gl_INT_IMAGE_2D_MULTISAMPLE_ARRAY_EXT = 36961
 
gl_INT_IMAGE_2D_MULTISAMPLE_EXT :: GLenum
gl_INT_IMAGE_2D_MULTISAMPLE_EXT = 36960
 
gl_INT_IMAGE_CUBE_MAP_ARRAY_EXT :: GLenum
gl_INT_IMAGE_CUBE_MAP_ARRAY_EXT = 36959
 
gl_INT_IMAGE_2D_ARRAY_EXT :: GLenum
gl_INT_IMAGE_2D_ARRAY_EXT = 36958
 
gl_INT_IMAGE_1D_ARRAY_EXT :: GLenum
gl_INT_IMAGE_1D_ARRAY_EXT = 36957
 
gl_INT_IMAGE_BUFFER_EXT :: GLenum
gl_INT_IMAGE_BUFFER_EXT = 36956
 
gl_INT_IMAGE_CUBE_EXT :: GLenum
gl_INT_IMAGE_CUBE_EXT = 36955
 
gl_INT_IMAGE_2D_RECT_EXT :: GLenum
gl_INT_IMAGE_2D_RECT_EXT = 36954
 
gl_INT_IMAGE_3D_EXT :: GLenum
gl_INT_IMAGE_3D_EXT = 36953
 
gl_INT_IMAGE_2D_EXT :: GLenum
gl_INT_IMAGE_2D_EXT = 36952
 
gl_INT_IMAGE_1D_EXT :: GLenum
gl_INT_IMAGE_1D_EXT = 36951
 
gl_IMAGE_2D_MULTISAMPLE_ARRAY_EXT :: GLenum
gl_IMAGE_2D_MULTISAMPLE_ARRAY_EXT = 36950
 
gl_IMAGE_2D_MULTISAMPLE_EXT :: GLenum
gl_IMAGE_2D_MULTISAMPLE_EXT = 36949
 
gl_IMAGE_CUBE_MAP_ARRAY_EXT :: GLenum
gl_IMAGE_CUBE_MAP_ARRAY_EXT = 36948
 
gl_IMAGE_2D_ARRAY_EXT :: GLenum
gl_IMAGE_2D_ARRAY_EXT = 36947
 
gl_IMAGE_1D_ARRAY_EXT :: GLenum
gl_IMAGE_1D_ARRAY_EXT = 36946
 
gl_IMAGE_BUFFER_EXT :: GLenum
gl_IMAGE_BUFFER_EXT = 36945
 
gl_IMAGE_CUBE_EXT :: GLenum
gl_IMAGE_CUBE_EXT = 36944
 
gl_IMAGE_2D_RECT_EXT :: GLenum
gl_IMAGE_2D_RECT_EXT = 36943
 
gl_IMAGE_3D_EXT :: GLenum
gl_IMAGE_3D_EXT = 36942
 
gl_IMAGE_2D_EXT :: GLenum
gl_IMAGE_2D_EXT = 36941
 
gl_IMAGE_1D_EXT :: GLenum
gl_IMAGE_1D_EXT = 36940
 
gl_IMAGE_BINDING_ACCESS_EXT :: GLenum
gl_IMAGE_BINDING_ACCESS_EXT = 36670
 
gl_IMAGE_BINDING_LAYER_EXT :: GLenum
gl_IMAGE_BINDING_LAYER_EXT = 36669
 
gl_IMAGE_BINDING_LAYERED_EXT :: GLenum
gl_IMAGE_BINDING_LAYERED_EXT = 36668
 
gl_IMAGE_BINDING_LEVEL_EXT :: GLenum
gl_IMAGE_BINDING_LEVEL_EXT = 36667
 
gl_IMAGE_BINDING_NAME_EXT :: GLenum
gl_IMAGE_BINDING_NAME_EXT = 36666
 
gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT :: GLenum
gl_MAX_COMBINED_IMAGE_UNITS_AND_FRAGMENT_OUTPUTS_EXT = 36665
 
gl_MAX_IMAGE_UNITS_EXT :: GLenum
gl_MAX_IMAGE_UNITS_EXT = 36664