{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.TextureEnvCombine
       (gl_OPERAND2_ALPHA_EXT, gl_OPERAND1_ALPHA_EXT,
        gl_OPERAND0_ALPHA_EXT, gl_OPERAND2_RGB_EXT, gl_OPERAND1_RGB_EXT,
        gl_OPERAND0_RGB_EXT, gl_SOURCE2_ALPHA_EXT, gl_SOURCE1_ALPHA_EXT,
        gl_SOURCE0_ALPHA_EXT, gl_SOURCE2_RGB_EXT, gl_SOURCE1_RGB_EXT,
        gl_SOURCE0_RGB_EXT, gl_PREVIOUS_EXT, gl_PRIMARY_COLOR_EXT,
        gl_CONSTANT_EXT, gl_INTERPOLATE_EXT, gl_ADD_SIGNED_EXT,
        gl_RGB_SCALE_EXT, gl_COMBINE_ALPHA_EXT, gl_COMBINE_RGB_EXT,
        gl_COMBINE_EXT)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_OPERAND2_ALPHA_EXT :: GLenum
gl_OPERAND2_ALPHA_EXT = 34202
 
gl_OPERAND1_ALPHA_EXT :: GLenum
gl_OPERAND1_ALPHA_EXT = 34201
 
gl_OPERAND0_ALPHA_EXT :: GLenum
gl_OPERAND0_ALPHA_EXT = 34200
 
gl_OPERAND2_RGB_EXT :: GLenum
gl_OPERAND2_RGB_EXT = 34194
 
gl_OPERAND1_RGB_EXT :: GLenum
gl_OPERAND1_RGB_EXT = 34193
 
gl_OPERAND0_RGB_EXT :: GLenum
gl_OPERAND0_RGB_EXT = 34192
 
gl_SOURCE2_ALPHA_EXT :: GLenum
gl_SOURCE2_ALPHA_EXT = 34186
 
gl_SOURCE1_ALPHA_EXT :: GLenum
gl_SOURCE1_ALPHA_EXT = 34185
 
gl_SOURCE0_ALPHA_EXT :: GLenum
gl_SOURCE0_ALPHA_EXT = 34184
 
gl_SOURCE2_RGB_EXT :: GLenum
gl_SOURCE2_RGB_EXT = 34178
 
gl_SOURCE1_RGB_EXT :: GLenum
gl_SOURCE1_RGB_EXT = 34177
 
gl_SOURCE0_RGB_EXT :: GLenum
gl_SOURCE0_RGB_EXT = 34176
 
gl_PREVIOUS_EXT :: GLenum
gl_PREVIOUS_EXT = 34168
 
gl_PRIMARY_COLOR_EXT :: GLenum
gl_PRIMARY_COLOR_EXT = 34167
 
gl_CONSTANT_EXT :: GLenum
gl_CONSTANT_EXT = 34166
 
gl_INTERPOLATE_EXT :: GLenum
gl_INTERPOLATE_EXT = 34165
 
gl_ADD_SIGNED_EXT :: GLenum
gl_ADD_SIGNED_EXT = 34164
 
gl_RGB_SCALE_EXT :: GLenum
gl_RGB_SCALE_EXT = 34163
 
gl_COMBINE_ALPHA_EXT :: GLenum
gl_COMBINE_ALPHA_EXT = 34162
 
gl_COMBINE_RGB_EXT :: GLenum
gl_COMBINE_RGB_EXT = 34161
 
gl_COMBINE_EXT :: GLenum
gl_COMBINE_EXT = 34160