{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.TextureCubeMap
       (gl_MAX_CUBE_MAP_TEXTURE_SIZE_EXT, gl_PROXY_TEXTURE_CUBE_MAP_EXT,
        gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_EXT,
        gl_TEXTURE_CUBE_MAP_POSITIVE_Z_EXT,
        gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_EXT,
        gl_TEXTURE_CUBE_MAP_POSITIVE_Y_EXT,
        gl_TEXTURE_CUBE_MAP_NEGATIVE_X_EXT,
        gl_TEXTURE_CUBE_MAP_POSITIVE_X_EXT,
        gl_TEXTURE_BINDING_CUBE_MAP_EXT, gl_TEXTURE_CUBE_MAP_EXT,
        gl_REFLECTION_MAP_EXT, gl_NORMAL_MAP_EXT)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_MAX_CUBE_MAP_TEXTURE_SIZE_EXT :: GLenum
gl_MAX_CUBE_MAP_TEXTURE_SIZE_EXT = 34076
 
gl_PROXY_TEXTURE_CUBE_MAP_EXT :: GLenum
gl_PROXY_TEXTURE_CUBE_MAP_EXT = 34075
 
gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_Z_EXT = 34074
 
gl_TEXTURE_CUBE_MAP_POSITIVE_Z_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_Z_EXT = 34073
 
gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_Y_EXT = 34072
 
gl_TEXTURE_CUBE_MAP_POSITIVE_Y_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_Y_EXT = 34071
 
gl_TEXTURE_CUBE_MAP_NEGATIVE_X_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_NEGATIVE_X_EXT = 34070
 
gl_TEXTURE_CUBE_MAP_POSITIVE_X_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_POSITIVE_X_EXT = 34069
 
gl_TEXTURE_BINDING_CUBE_MAP_EXT :: GLenum
gl_TEXTURE_BINDING_CUBE_MAP_EXT = 34068
 
gl_TEXTURE_CUBE_MAP_EXT :: GLenum
gl_TEXTURE_CUBE_MAP_EXT = 34067
 
gl_REFLECTION_MAP_EXT :: GLenum
gl_REFLECTION_MAP_EXT = 34066
 
gl_NORMAL_MAP_EXT :: GLenum
gl_NORMAL_MAP_EXT = 34065