{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.EXT.TextureSRGB
       (gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT,
        gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT,
        gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT,
        gl_COMPRESSED_SRGB_S3TC_DXT1_EXT,
        gl_COMPRESSED_SLUMINANCE_ALPHA_EXT, gl_COMPRESSED_SLUMINANCE_EXT,
        gl_COMPRESSED_SRGB_ALPHA_EXT, gl_COMPRESSED_SRGB_EXT,
        gl_SLUMINANCE8_EXT, gl_SLUMINANCE_EXT, gl_SLUMINANCE8_ALPHA8_EXT,
        gl_SLUMINANCE_ALPHA_EXT, gl_SRGB8_ALPHA8_EXT, gl_SRGB_ALPHA_EXT,
        gl_SRGB8_EXT, gl_SRGB_EXT)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT5_EXT = 35919
 
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT3_EXT = 35918
 
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_S3TC_DXT1_EXT = 35917
 
gl_COMPRESSED_SRGB_S3TC_DXT1_EXT :: GLenum
gl_COMPRESSED_SRGB_S3TC_DXT1_EXT = 35916
 
gl_COMPRESSED_SLUMINANCE_ALPHA_EXT :: GLenum
gl_COMPRESSED_SLUMINANCE_ALPHA_EXT = 35915
 
gl_COMPRESSED_SLUMINANCE_EXT :: GLenum
gl_COMPRESSED_SLUMINANCE_EXT = 35914
 
gl_COMPRESSED_SRGB_ALPHA_EXT :: GLenum
gl_COMPRESSED_SRGB_ALPHA_EXT = 35913
 
gl_COMPRESSED_SRGB_EXT :: GLenum
gl_COMPRESSED_SRGB_EXT = 35912
 
gl_SLUMINANCE8_EXT :: GLenum
gl_SLUMINANCE8_EXT = 35911
 
gl_SLUMINANCE_EXT :: GLenum
gl_SLUMINANCE_EXT = 35910
 
gl_SLUMINANCE8_ALPHA8_EXT :: GLenum
gl_SLUMINANCE8_ALPHA8_EXT = 35909
 
gl_SLUMINANCE_ALPHA_EXT :: GLenum
gl_SLUMINANCE_ALPHA_EXT = 35908
 
gl_SRGB8_ALPHA8_EXT :: GLenum
gl_SRGB8_ALPHA8_EXT = 35907
 
gl_SRGB_ALPHA_EXT :: GLenum
gl_SRGB_ALPHA_EXT = 35906
 
gl_SRGB8_EXT :: GLenum
gl_SRGB8_EXT = 35905
 
gl_SRGB_EXT :: GLenum
gl_SRGB_EXT = 35904