{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.NV.TextureShader3
       (gl_SIGNED_HILO8, gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE,
        gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE,
        gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE,
        gl_OFFSET_PROJECTIVE_TEXTURE_2D, gl_OFFSET_HILO_TEXTURE_RECTANGLE,
        gl_OFFSET_HILO_TEXTURE_2D,
        gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE,
        gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D, gl_HILO8,
        gl_FORCE_BLUE_TO_ONE, gl_DOT_PRODUCT_TEXTURE_1D,
        gl_DOT_PRODUCT_PASS_THROUGH, gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE,
        gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP, gl_DEPENDENT_RGB_TEXTURE_3D,
        gl_DEPENDENT_HILO_TEXTURE_2D)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_SIGNED_HILO8 :: GLenum
gl_SIGNED_HILO8 = 34911
 
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE = 34899
 
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE = 34898
 
gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE = 34897
 
gl_OFFSET_PROJECTIVE_TEXTURE_2D :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_2D = 34896
 
gl_OFFSET_HILO_TEXTURE_RECTANGLE :: GLenum
gl_OFFSET_HILO_TEXTURE_RECTANGLE = 34901
 
gl_OFFSET_HILO_TEXTURE_2D :: GLenum
gl_OFFSET_HILO_TEXTURE_2D = 34900
 
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE :: GLenum
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE = 34903
 
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D :: GLenum
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D = 34902
 
gl_HILO8 :: GLenum
gl_HILO8 = 34910
 
gl_FORCE_BLUE_TO_ONE :: GLenum
gl_FORCE_BLUE_TO_ONE = 34912
 
gl_DOT_PRODUCT_TEXTURE_1D :: GLenum
gl_DOT_PRODUCT_TEXTURE_1D = 34908
 
gl_DOT_PRODUCT_PASS_THROUGH :: GLenum
gl_DOT_PRODUCT_PASS_THROUGH = 34907
 
gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE :: GLenum
gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE = 34909
 
gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP :: GLenum
gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP = 34906
 
gl_DEPENDENT_RGB_TEXTURE_3D :: GLenum
gl_DEPENDENT_RGB_TEXTURE_3D = 34905
 
gl_DEPENDENT_HILO_TEXTURE_2D :: GLenum
gl_DEPENDENT_HILO_TEXTURE_2D = 34904