{-# LANGUAGE ForeignFunctionInterface #-}
{-# LANGUAGE CPP #-}
module Graphics.Rendering.OpenGL.Raw.NV.TextureShader3
       (gl_FORCE_BLUE_TO_ONE_NV, gl_SIGNED_HILO8_NV, gl_HILO8_NV,
        gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV,
        gl_DOT_PRODUCT_TEXTURE_1D_NV, gl_DOT_PRODUCT_PASS_THROUGH_NV,
        gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV,
        gl_DEPENDENT_RGB_TEXTURE_3D_NV, gl_DEPENDENT_HILO_TEXTURE_2D_NV,
        gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV,
        gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV,
        gl_OFFSET_HILO_TEXTURE_RECTANGLE_NV, gl_OFFSET_HILO_TEXTURE_2D_NV,
        gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV,
        gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV,
        gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV,
        gl_OFFSET_PROJECTIVE_TEXTURE_2D_NV)
       where
import Graphics.Rendering.OpenGL.Raw.Internal.TypesInternal
import Foreign.Ptr
import Graphics.Rendering.OpenGL.Raw.Internal.Extensions
 
gl_FORCE_BLUE_TO_ONE_NV :: GLenum
gl_FORCE_BLUE_TO_ONE_NV = 34912
 
gl_SIGNED_HILO8_NV :: GLenum
gl_SIGNED_HILO8_NV = 34911
 
gl_HILO8_NV :: GLenum
gl_HILO8_NV = 34910
 
gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV :: GLenum
gl_DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV = 34909
 
gl_DOT_PRODUCT_TEXTURE_1D_NV :: GLenum
gl_DOT_PRODUCT_TEXTURE_1D_NV = 34908
 
gl_DOT_PRODUCT_PASS_THROUGH_NV :: GLenum
gl_DOT_PRODUCT_PASS_THROUGH_NV = 34907
 
gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV :: GLenum
gl_DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV = 34906
 
gl_DEPENDENT_RGB_TEXTURE_3D_NV :: GLenum
gl_DEPENDENT_RGB_TEXTURE_3D_NV = 34905
 
gl_DEPENDENT_HILO_TEXTURE_2D_NV :: GLenum
gl_DEPENDENT_HILO_TEXTURE_2D_NV = 34904
 
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV = 34903
 
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV :: GLenum
gl_OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV = 34902
 
gl_OFFSET_HILO_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_HILO_TEXTURE_RECTANGLE_NV = 34901
 
gl_OFFSET_HILO_TEXTURE_2D_NV :: GLenum
gl_OFFSET_HILO_TEXTURE_2D_NV = 34900
 
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV = 34899
 
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV = 34898
 
gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV = 34897
 
gl_OFFSET_PROJECTIVE_TEXTURE_2D_NV :: GLenum
gl_OFFSET_PROJECTIVE_TEXTURE_2D_NV = 34896